spec:
  structures:
    - buttonBlocks
  label: Button
  description: "A clickable element that navigates to another page or triggers an action within the current page."
  icon: rectangle
  tags: []

blueprint:
  text:
  link:
  iconName:
  iconPosition: before
  hideText: false
  variant: ghost
  size: md

preview:

_inputs:
  text:
    type: text
    comment: The text that goes inside the button.
  link:
    type: url
    comment: The URL that the button should link to.
  iconName:
    type: select
    options:
      values: _select_data.icons
    comment: The name of the icon to display. See the Icon component documentation for more information.
  iconPosition:
    type: select
    options:
      values:
        - name: Before
          value: before
        - name: After
          value: after
      value_key: value
    comment: The position of the icon relative to the text.
  hideText:
    type: switch
    comment: Whether to hide the button text and show only the icon.
  variant:
    type: select
    options:
      values:
        - name: Primary
          value: primary
        - name: Secondary
          value: secondary
        - name: Tertiary
          value: tertiary
        - name: Ghost
          value: ghost
        - name: Text
          value: text
      value_key: value
    comment: The presentation of button.
  size:
    type: select
    options:
      values:
        - name: Small
          value: sm
        - name: Medium
          value: md
        - name: Large
          value: lg
      value_key: value
    comment: The size of the button.
