spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Definition List
  description: "Useful for displaying key-value pairs, ideal for glossaries, opening times, etc."
  icon: dns
  tags: []

blueprint:
  items:
  horizontalAlignment: start

preview:

_inputs:
  items:
    type: array
    options:
      structures: _structures.item
  horizontalAlignment:
    type: select
    options:
      values:
        - value: start
          name: Start
        - value: center
          name: Center
        - value: end
          name: End
      value_key: value
      preview:
        text:
          - key: name

_structures:
  item:
    values:
      - label: Definition List Item
        icon: title
        value:
          title:
          text:
