# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Nav Bar
  description: "A responsive navigation bar component that displays both desktop and mobile navigation with dropdown support, logo, and action buttons."
  icon: navigation
  tags: ["navigation", "header", "responsive"]

# Defines the structure of this component, as well as the default values
blueprint:
  label: "Main Navigation"
  logoSource: ""
  logoAlt: "Logo"
  navData:
  buttonBlocks:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    type: text
    comment: "Optional label for the navigation bar to help identify it in the editor."
  logoSource:
    type: image
    comment: "Logo image source URL or path. Leave empty to hide the logo."
  logoAlt:
    type: text
    comment: "Alt text for the logo image for accessibility."
  navData:
    type: array
    comment: "Array of navigation items to render in the navigation bar. Supports up to 3 levels of nesting."
    _inputs:
      name:
        type: text
        comment: "Display text for the navigation item."
      path:
        type: text
        comment: "URL path for the navigation item."
      children:
        type: array
        comment: "Child navigation items for dropdown menus."
        _inputs:
          name:
            type: text
            comment: "Display text for the child navigation item."
          path:
            type: text
            comment: "URL path for the child navigation item."
          children:
            type: array
            comment: "Grandchild navigation items for nested dropdowns."
            _inputs:
              name:
                type: text
                comment: "Display text for the grandchild navigation item."
              path:
                type: text
                comment: "URL path for the grandchild navigation item."
  buttonBlocks:
    type: array
    comment: "Array of button components to display in the navigation bar (typically on the right side)."
    _inputs:
      _bookshop_name:
        type: text
        comment: "Component name - should be 'elements/button'."
      link:
        type: text
        comment: "URL or path for the button link."
      text:
        type: text
        comment: "Button text content."
      variant:
        type: select
        comment: "Button style variant."
        options:
          - "primary"
          - "secondary"
          - "tertiary"
          - "ghost"
      size:
        type: select
        comment: "Button size."
        options:
          - "xs"
          - "sm"
          - "md"
          - "lg"
          - "xl"
      iconName:
        type: text
        comment: "Optional icon name to display in the button."
      iconPosition:
        type: select
        comment: "Position of the icon relative to text."
        options:
          - "before"
          - "after"
      hideText:
        type: boolean
        comment: "Whether to hide the button text and show only the icon."
